apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-nd-capstone
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-nd-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devops-nd-capstone
    spec:
      containers:
        - name: devops-nd-capstone
          image: rahul14m93/devops_capstone_nd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: devops-nd-capstone
  labels:
    app: devops-nd-capstone
spec:
  type: LoadBalancer
  selector:
    app: devops-nd-capstone
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP